parserOptions:
  ecmaVersion: 2017
  sourceType: 'module'

env:
  es6: true
  node: true
  commonjs: true
  browser: true
  mocha: true

rules:
  no-eval:
    - error
    - allowIndirect: true

extends: 'htmlacademy/node'

