export const Class = Object.freeze({
  HEADER: `js-header`,
  TEST: `js-test`,
  TEST_TAG: `js-test__tag`,
  TEST_TITLE: `js-test__title`,
  TEST_LEAD_TEXT: `js-test__lead-text`,
  TEST_IS_CHECKED: `test--is-checked`,
  TEST_QUESTIONS: `js-test__questions`,
  TEST_SOCIAL: `js-test__social`,
  SUMMARY_SHARE_FB: `js-summary__share-btn--fb`,
  // SUMMARY_SHARE_FB2: `js-summary__share-btn--fb2`,
  SUMMARY_SHARE_VK: `js-summary__share-btn--vk`,
  SUMMARY_SHARE_TW: `js-summary__share-btn--tw`,
  TEST_SOCIAL_VISIBLE: `test__social--visible`,
  TEST_QUESTIONS_DONE: `test__questions--done`,
  RESULT_BTN: `js-test__result-btn`,
  RESULT_BTN_VISIBLE: `test__result-btn--visible`,
  RETAKE_BLOCK: `js-test__retake-block`,
  RETAKE_BLOCK_VISIBLE: `test__retake-block--visible`,
  RETAKE_BTN: `js-test__retake-btn`,
  RETAKE_MESSAGE: `js-test__retake-message`,
  QUESTION: `js-question`,
  QUESTION_OPTIONS: `js-question__options`,
  QUESTION_OPTION: `js-question__option`,
  QUESTION_OPTION_IS_CHECKED: `question__option--is-checked`,
  QUESTION_WRONG: `question--wrong`,
  TEST_SHARE_FB: `js-test__share-fb`,
  TEST_LIKE_FB: `js-test__like-fb`,
  TEST_DISQUS_VISIBLE: `test__disqus--visible`,
  TEST_DISQUS: `js-test__disqus`
});
